### ISSUE TITLE
[FEAT] Remove unneccesary sections of the repo

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [Sonichigo/Postgram#1]
Hey Sonichigo. Nice project these are few suggestions from my side

1. Please remove unwanted sections from the repo
<img src="https://i.imgur.com/9pzyf0F.png">

2. Add a description of the repo
<img src="https://i.imgur.com/VeyKP7t.png">

3. It seems that you are using the auto-generated template of React. Personalizing it from start would look more awesome

**Comment by Sonichigo** [comment]
Thanks, made the changes!!
